model: mlx-community/Qwen2.5-1.5B-Instruct-4bit
revision: 8b403126fc14f14cfc99bb4cfa72ecbc129ea677
seed: 2
batch_size: 2
grad_accumulation_steps: 8
iters: 180
learning_rate: 0.00002
num_layers: 16
max_seq_length: 2048
val_batches: -1
steps_per_report: 5
steps_per_eval: 45
save_every: 45
rank: 16
dropout: 0.05
scale: 32.0
mask_prompt: true
grad_checkpoint: true
