model: mlx-community/Qwen2.5-0.5B-Instruct-4bit
revision: 53a32aee5e9447773fd2b85988395066aef3700a
seed: 0
batch_size: 2
grad_accumulation_steps: 8
iters: 180
learning_rate: 0.00002
num_layers: 16
max_seq_length: 1024
val_batches: -1
steps_per_report: 5
steps_per_eval: 45
save_every: 45
rank: 16
dropout: 0.05
scale: 32.0
mask_prompt: true
grad_checkpoint: false
